version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: shinewardrobe-postgres-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: shinewardrobe-backend-dev
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - NODE_ENV=development
      - PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    command: bun --watch src/index.ts
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: shinewardrobe-frontend-dev
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:${BACKEND_PORT}
      - NODE_ENV=development
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    command: bun dev
    restart: unless-stopped

  webscraper:
    build:
      context: ./webscraper
      dockerfile: Dockerfile.dev
    container_name: shinewardrobe-scraper-dev
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SCRAPER_SCHEDULE=${SCRAPER_SCHEDULE}
      - SCRAPER_MAX_PRODUCTS=${SCRAPER_MAX_PRODUCTS}
    volumes:
      - ./webscraper:/app
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data_dev:

networks:
  default:
    name: shinewardrobe-network-dev