name: shinewardrobe

services:
  postgres:
    image: postgres:15-alpine
    container_name: shinewardrobe-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: shinewardrobe
      POSTGRES_PASSWORD: shinewardrobe123
      POSTGRES_DB: shinewardrobe
    ports:
      - "5432:5432"
    volumes:
      - ./backend/src/migrations:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shinewardrobe -d shinewardrobe"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shinewardrobe-net

  ollama:
    image: ollama/ollama:latest
    container_name: shinewardrobe-ai
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - shinewardrobe-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shinewardrobe-api
    restart: unless-stopped
    # Variáveis de ambiente carregadas do arquivo .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3.2:3b
      - NODE_ENV=development
      - PORT=${BACKEND_PORT}
      - CORS_ORIGIN=*
    ports:
      # Mapeia a porta definida em .env para a porta do host
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shinewardrobe-net
    command: >
      sh -c "
        echo 'Banco de dados pronto. Iniciando backend...' &&
        bun --watch src/index.ts
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shinewardrobe-web
    restart: unless-stopped
    environment:
      # Esta variável precisa do valor da porta do backend
      - NEXT_PUBLIC_API_URL=http://localhost:${BACKEND_PORT}
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - shinewardrobe-net

volumes:
  postgres_data:
    driver: local
  ollama_data:
    driver: local

networks:
  shinewardrobe-net:
    driver: bridge